---
swagger: "2.0"
info:
  version: 1.0-SNAPSHOT
  title: “lesson 1”
basePath: /v1
paths:
  /accounts/{id}:
    get:
      description: Simple get mock.
      operationId: accounts/getBalance
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
  /accounts:
    get:
      description: Query Account
      operationId: accounts/queryAccount
      parameters:
      - in: query
        name: customerId
        type: integer
        description: Customer Id
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
    post:
      description: Create Account
      operationId: accounts/createAccount
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
    